### ISSUE TITLE
missing loot tracking

### ISSUE THREAD

**Issue by FanaticalSoul** [FanaticalSoul/dstcg#11]
- [ ] track encounter rewards ( including their loss )
- [ ] track souls ( including their loss )
- [ ] track loot ( including their loss )
- [ ] track inventory
