### ISSUE TITLE
missing win and loss tracking

### ISSUE THREAD

**Issue by FanaticalSoul** [FanaticalSoul/dstcg#34]
- [ ] track and display total wins and losses ( use save file )
- [ ] show win screen ( press any key to exit )
- [ ] show loss screen ( press any key to exit )
